apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels: 
    name: application
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: app-deployment
  namespace: app
spec:
  replicas: 2
  template:
    metadata:
      name: spring-boot-app
      labels:
        name: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: app-http
          containerPort: 8080
